{% set name = "tellurium" %}
{% set version = "2.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 2.1.5
  git_url: https://github.com/sys-bio/tellurium

requirements:
  build:
    - python
    - setuptools
  run:
    - roadrunner
    - antimony
    - phrasedml
    - libsedml

about:
  home: http://tellurium.analogmachine.org/

extra:
  maintainers:
   - Kyle Medley (https://github.com/0u812)

